services:
  app:
    build:
      context: .
      dockerfile: python.Dockerfile
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
    tty: true
    stdin_open: true
    command: uv run python src/main.py
