services:
  benchmark:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
      - ./src:/app/src
      - ./conf:/app/conf
      - ./prompts:/app/prompts
    tty: true
    stdin_open: true
